[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/"
]

[profile.ci]
src = "src"
out = "out"
libs = ["lib"]
fuzz = { runs = 5000 }
invariant = { runs = 1000 }

# RPC URLs
[rpc_endpoints]
base_sepolia = "https://sepolia.base.org"

# Etherscan API keys for verification
[etherscan]
base_sepolia = { key = "${BASESCAN_API_KEY}", url = "https://api-sepolia.basescan.org/api" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
